import type { Metadata } from "next";
import "./globals.css";
import { inter, montserrat } from "./ui/fonts";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${montserrat.className} first-line:${inter.className} antialiased bg-blue-600`}
      >
        {children}
      </body>
    </html>
  );
}
